// <auto-generated />
using System;
using FrugalBites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrugalBites.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120135146_AddPickupIntervalToOrder")]
    partial class AddPickupIntervalToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FrugalBites.Models.Entities.Analytics", b =>
                {
                    b.Property<Guid>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("AnalyticsId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<DateOnly>("DateRecorded")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateRecorded");

                    b.Property<decimal>("FoodSavedKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("FoodSavedKg");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<int>("OffersCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OffersCreated");

                    b.Property<int>("OffersPurchased")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OffersPurchased");

                    b.Property<decimal>("RevenueGenerated")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("RevenueGenerated");

                    b.Property<TimeOnly?>("TopOrderTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("TopOrderTime");

                    b.HasKey("AnalyticsId");

                    b.HasIndex("MerchantId", "DateRecorded")
                        .IsUnique();

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Favorite", b =>
                {
                    b.Property<Guid>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("FavoriteId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("FavoriteId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("UserId", "MerchantId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Merchant", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("TEXT")
                        .HasColumnName("AverageRating");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("BusinessName");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BusinessType");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("City");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CommissionRate");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("CoverImageUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsVerified");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT")
                        .HasColumnName("Latitude");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("LogoUrl");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT")
                        .HasColumnName("Longitude");

                    b.Property<string>("OperatingHoursJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("OperatingHoursJson");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("PickupInstructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupInstructions");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PostalCode");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("StripeAccountId");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalReviews");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("WebsiteUrl");

                    b.HasKey("MerchantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            MerchantId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AddressLine1 = "Intrarea Catedrei, 5",
                            AverageRating = 4.5m,
                            BusinessName = "Pizza Roma",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic Italian pizza and pasta near Cathedral",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4268m,
                            LogoUrl = "https://images.unsplash.com/photo-1608270861620-7299b3e330f0?w=100&h=100&fit=crop",
                            Longitude = 26.0881m,
                            PostalCode = "030015",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MerchantId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AddressLine1 = "Intrarea Catedrei, 12",
                            AverageRating = 4.8m,
                            BusinessName = "Sushi Palace",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh sushi and Asian cuisine in the heart of Bucharest",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4275m,
                            LogoUrl = "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=100&h=100&fit=crop",
                            Longitude = 26.0890m,
                            PostalCode = "030015",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MerchantId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AddressLine1 = "Calea Victoriei, 42",
                            AverageRating = 4.3m,
                            BusinessName = "Burger House",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium burgers and gourmet fast food",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4260m,
                            LogoUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=100&h=100&fit=crop",
                            Longitude = 26.0870m,
                            PostalCode = "030023",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MerchantId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AddressLine1 = "Calea Victoriei, 156",
                            AverageRating = 4.6m,
                            BusinessName = "Pho Vietnam",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic Vietnamese street food and pho",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4235m,
                            LogoUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=100&h=100&fit=crop",
                            Longitude = 26.0945m,
                            PostalCode = "020022",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            MerchantId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            AddressLine1 = "Strada Grozavesti, 23",
                            AverageRating = 4.7m,
                            BusinessName = "Artisan Cafe",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specialty coffee and artisan pastries",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4650m,
                            LogoUrl = "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=100&h=100&fit=crop",
                            Longitude = 26.0580m,
                            PostalCode = "020748",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            MerchantId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            AddressLine1 = "Strada Regie, 8",
                            AverageRating = 4.4m,
                            BusinessName = "Taverna Athena",
                            BusinessType = "RESTAURANT",
                            City = "Bucharest",
                            CommissionRate = 5.0m,
                            CountryCode = "RO",
                            CoverImageUrl = "https://images.unsplash.com/photo-1555939594-58d7cb561482?w=500&h=200&fit=crop",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional Greek cuisine and mezze plates",
                            IsActive = true,
                            IsVerified = false,
                            Latitude = 44.4645m,
                            LogoUrl = "https://images.unsplash.com/photo-1555939594-58d7cb561482?w=100&h=100&fit=crop",
                            Longitude = 26.0595m,
                            PostalCode = "020756",
                            TotalReviews = 0,
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Offer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("OfferId");

                    b.Property<string>("AllergensJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("AllergensJson");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Dietary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Dietary");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DiscountPercentage");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DiscountedPrice");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("FoodName");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsAvailable");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OriginalPrice");

                    b.Property<DateTime>("PickupEndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupEndTime");

                    b.Property<DateTime>("PickupStartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupStartTime");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("QuantityUnit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("OfferId");

                    b.HasIndex("MerchantId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            OfferId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic Margherita pizza with fresh mozzarella and basil",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 20.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Margherita Pizza",
                            ImageUrl = "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            OriginalPrice = 40.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 3,
                            QuantityUnit = "PIECE",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Four cheese pizza with ricotta, mozzarella, parmesan and gorgonzola",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 25.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Quattro Formaggi",
                            ImageUrl = "https://images.unsplash.com/photo-1571407-918cfff43dfb?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            OriginalPrice = 50.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 2,
                            QuantityUnit = "PIECE",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh salmon, avocado, and cucumber sushi roll - 8 pieces",
                            Dietary = "NONE",
                            DiscountPercentage = 50,
                            DiscountedPrice = 30.00m,
                            ExpirationDate = new DateOnly(2026, 1, 14),
                            FoodName = "Salmon Sushi Roll",
                            ImageUrl = "https://images.unsplash.com/photo-1553621042-f6e147245ba1?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            OriginalPrice = 60.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 2,
                            QuantityUnit = "PACK",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assorted fresh vegetables in light tempura batter",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 19.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Vegetable Tempura",
                            ImageUrl = "https://images.unsplash.com/photo-1611680626919-8cf0cab20c51?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            OriginalPrice = 38.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 4,
                            QuantityUnit = "PORTION",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Juicy beef patty with cheddar cheese, lettuce, tomato and special sauce",
                            Dietary = "NONE",
                            DiscountPercentage = 50,
                            DiscountedPrice = 24.00m,
                            ExpirationDate = new DateOnly(2026, 1, 14),
                            FoodName = "Classic Cheeseburger",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            OriginalPrice = 48.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 5,
                            QuantityUnit = "PIECE",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plant-based burger with grilled vegetables and vegan mayo",
                            Dietary = "NONE",
                            DiscountPercentage = 50,
                            DiscountedPrice = 21.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Veggie Burger",
                            ImageUrl = "https://images.unsplash.com/photo-1581887720020-91ec17a7a568?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            OriginalPrice = 42.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 3,
                            QuantityUnit = "PIECE",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traditional Vietnamese beef pho with broth and rice noodles",
                            Dietary = "NONE",
                            DiscountPercentage = 50,
                            DiscountedPrice = 22.50m,
                            ExpirationDate = new DateOnly(2026, 1, 14),
                            FoodName = "Beef Pho",
                            ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            OriginalPrice = 45.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 4,
                            QuantityUnit = "PORTION",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh vegetarian pho with tofu and seasonal vegetables",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 20.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Vegetarian Pho",
                            ImageUrl = "https://images.unsplash.com/photo-1588013273468-315fd88ea343?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            OriginalPrice = 40.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 3,
                            QuantityUnit = "PORTION",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh butter croissant with premium espresso or cappuccino",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 16.00m,
                            ExpirationDate = new DateOnly(2026, 1, 14),
                            FoodName = "Croissant & Coffee Bundle",
                            ImageUrl = "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            OriginalPrice = 32.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 6,
                            QuantityUnit = "PACK",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delicate almond croissant with sliced almonds and powdered sugar",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 14.00m,
                            ExpirationDate = new DateOnly(2026, 1, 14),
                            FoodName = "Almond Croissant",
                            ImageUrl = "https://images.unsplash.com/photo-1527521481379-d28b9fce3586?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            OriginalPrice = 28.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 4,
                            QuantityUnit = "PIECE",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mix of tzatziki, hummus, feta, olives, bread and vegetables",
                            Dietary = "VEGETARIAN",
                            DiscountPercentage = 50,
                            DiscountedPrice = 35.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Greek Mezze Platter",
                            ImageUrl = "https://images.unsplash.com/photo-1555939594-58d7cb561482?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            OriginalPrice = 70.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 2,
                            QuantityUnit = "PACK",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            OfferId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "PREPARED_MEALS",
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tender lamb souvlaki with pita bread and lemon potato",
                            Dietary = "NONE",
                            DiscountPercentage = 50,
                            DiscountedPrice = 34.00m,
                            ExpirationDate = new DateOnly(2026, 1, 15),
                            FoodName = "Grilled Lamb Souvlaki",
                            ImageUrl = "https://images.unsplash.com/photo-1599599810694-b3da7dd22d1d?w=300&h=200&fit=crop",
                            IsAvailable = true,
                            MerchantId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            OriginalPrice = 68.00m,
                            PickupEndTime = new DateTime(2026, 1, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            PickupStartTime = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Quantity = 2,
                            QuantityUnit = "PACK",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderId");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("CancelReason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerNotes");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DiscountAmount");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OfferId");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderStatus");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("PaymentMethodId");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PaymentStatus");

                    b.Property<DateTime?>("PickupConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupConfirmedAt");

                    b.Property<DateTime?>("PickupEndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupEndTime");

                    b.Property<DateTime?>("PickupStartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupStartTime");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PickupTime");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("StripePaymentIntentId");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalPrice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("OrderId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OfferId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderId");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewText");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("ReviewId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("TransactionId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Amount");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CommissionAmount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("MerchantEarnings")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MerchantEarnings");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MerchantId");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OrderId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TransactionType");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("TransactionId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsEmailVerified");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsPhoneVerified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserType");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pizzaroma@restaurant.com",
                            FirstName = "Pizza",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Roma",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sushi@restaurant.com",
                            FirstName = "Sushi",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Palace",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "burgers@restaurant.com",
                            FirstName = "Burger",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "House",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vietnamese@restaurant.com",
                            FirstName = "Pho",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Vietnam",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cafe@restaurant.com",
                            FirstName = "Artisan",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Cafe",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        },
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "greek@restaurant.com",
                            FirstName = "Taverna",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsPhoneVerified = false,
                            LastName = "Athena",
                            PasswordHash = "",
                            UpdatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserType = "MERCHANT"
                        });
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Analytics", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Analytics")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Favorite", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Favorites")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Merchant", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.User", "User")
                        .WithOne("Merchant")
                        .HasForeignKey("FrugalBites.Models.Entities.Merchant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Offer", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Offers")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Order", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Orders")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.Offer", "Offer")
                        .WithMany("Orders")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Review", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Reviews")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("FrugalBites.Models.Entities.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Transaction", b =>
                {
                    b.HasOne("FrugalBites.Models.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("FrugalBites.Models.Entities.Transaction", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrugalBites.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Merchant", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("Favorites");

                    b.Navigation("Offers");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Offer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.Order", b =>
                {
                    b.Navigation("Review");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FrugalBites.Models.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Merchant");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
